# Generated by Django 5.0.4 on 2026-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полный текст')),
                ('image_url', models.URLField(blank=True, help_text='Прямая ссылка на изображение, например: https://i.imgur.com/abc.jpg', max_length=500, verbose_name='Ссылка на фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-published_at', '-created_at', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='robots/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('monitoring', 'Мониторинг'), ('rescue', 'Спасательные операции'), ('sensors', 'Датчики и модули')], default='monitoring', max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='Список URL изображений, например: ["/media/robots/1.jpg", "/media/robots/2.jpg"]', verbose_name='Галерея (ссылки на изображения)')),
                ('length_m', models.FloatField(default=2.0, verbose_name='Длина, м')),
                ('width_m', models.FloatField(default=1.0, verbose_name='Ширина, м')),
                ('weight_kg', models.FloatField(default=12.0, verbose_name='Масса, кг')),
                ('max_speed_kmh', models.FloatField(default=5.0, verbose_name='Макс. скорость, км/ч')),
                ('autonomy_hours', models.FloatField(default=2.0, verbose_name='Автономность, ч')),
                ('range_km', models.FloatField(default=5.0, verbose_name='Запас хода, км')),
                ('payload_kg', models.FloatField(default=2.0, verbose_name='Полезная нагрузка, кг')),
                ('control_range_km', models.FloatField(default=1.0, verbose_name='Дальность управления, км')),
                ('battery_capacity_mah', models.PositiveIntegerField(default=10000, verbose_name='Ёмкость АКБ, мА·ч')),
                ('ip_rating', models.CharField(default='IP67', max_length=16, verbose_name='Класс защиты')),
                ('min_temperature_c', models.FloatField(default=5.0, verbose_name='Мин. температура, °C')),
                ('max_wind_ms', models.FloatField(default=8.0, verbose_name='Макс. ветер, м/с')),
                ('supports_camera', models.BooleanField(default=True, verbose_name='Видеокамера')),
                ('supports_water_sensors', models.BooleanField(default=True, verbose_name='Датчики качества воды')),
                ('supports_beacon', models.BooleanField(default=True, verbose_name='Свето-звуковой маяк')),
                ('supports_tug', models.BooleanField(default=True, verbose_name='Буксировка лёгких предметов')),
            ],
            options={
                'verbose_name': 'Роботизированная платформа',
                'verbose_name_plural': 'Роботизированные платформы',
                'ordering': ['id'],
            },
        ),
    ]
