# Generated by Django 6.1.1 on 2026-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prosthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to='prostheses/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('legs', 'Для ног'), ('arms', 'Для рук'), ('cosmetic', 'Косметические')], default='legs', max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Протез',
                'verbose_name_plural': 'Протезы',
                'ordering': ['id'],
            },
        ),
    ]
