# Generated by Django 5.0.4 on 2026-09-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='image',
        ),
        migrations.AddField(
            model_name='robot',
            name='image_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на изображение, например: https://i.imgur.com/abc.jpg', max_length=500, verbose_name='Ссылка на фото'),
        ),
    ]
